# 45. Promise

- 자바스크립트는 비동기 처리를 위한 하나의 패턴으로 콜백함수를 사용한다.
- 전통적인 콜백 패턴은 콜백 헬로 인해 가독성이 나쁘고 비동기 처리 중 발생한 에러의 처리가 곤란하며 여러 개의 비동기 처리를 한번에 처리하는데도 한계가 있다.
- ES6에서는 비동기 처리를 위한 다른 패턴으로 프로미스를 도입했다.

## 45-1. 비동기 처리를 위한 콜백 패턴의 단점

### 45-1-1. 콜백 헬

```javascript
// GET 요청
const get = url => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      // 서버의 응답을 콘솔에 출력한다.
      console.log(JSON.parse(xhr.response));
    } else {
      console.err(`${xhr.status} ${xhr.statusText}`)
    }
  };
};

get('https://jsonplaceholder.typicode.com/posts/1');
```

- 위 get 함수는 비동기 함수다.
- 비동기 함수를 호출하면 함수 내부의 비동기로 동작하는 코드가 완료되지 않았다 해도 기다리지 않고 즉시 종료된다.
- 비동기 함수의 처리 결과에 대한 후속 처리는 비동기 함수 내부에서 수행해야 한다.

```javascript
// GET 요청
const get = (url, successCallback, failCallback) => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      // 서버의 응답을 콘솔에 출력한다.
      successCallback(JSON.parse(xhr.response));
    } else {
      failCallback(`${xhr.status} ${xhr.statusText}`)
    }
  };
};

get('https://jsonplaceholder.typicode.com/posts/1', console.log, console.error);
```

- 콜백함수를 통해 비동기 처리 결과에 대한 후속 처리를 수행하는 비동기 함수가 비동기 처리 결과를 가지고 또다시 비동기 함수를 호출해야 한다면 콜백함수 호출이 중첩되어 복잡도가 높아지는 현상이 발생한다.

```javascript
  // callback hell
get('/step1', a => {
  get(`/step2/${a}`, b => {
    get(`/step3/${b}`, c => {
      get(`/step4/${c}`, d => {
        console.log(d);
      });
    });
  });
});
```

### 45-1-2. 에러 처리의 한계

```javascript
try {
  setTimeout(() => { throw new Error('Error!'); }, 1000);
} catch (e) {
  // 에러를 캐치하지 못한다.
  console.error('캐치한 에러', e);
}
```

> try...catch...finally문  
> 에러 처리를 구현하는 방법. try 코드 블록이 먼저 실행된다. try 문에서 에러가 발생하면 해당 에러는 catch문의 err변수에 전달되고 catch 블록이 실행된다.  
> finally문은 에러 발생 여부에 상관없이 반드시 한번 실행된다. try catch문으로 에러를 처리하면 프로그램이 강제 종료되지 않는다.

- 에러는 호출자 방향으로 전파 된다.
- 콜 스택의 아래 방향(실행중인 실행 컨텍스트가 푸시되기 직전에 푸시된 실행 컨텍스트 방향)으로 전파된다.
- 이런 비동기 처리를 위한 콜백 패턴은 콜백 헬과 에러 처리가 곤란하다는 문제가 있고, 이를 위해 프로미스가 도입됨.

## 45-2. 프로미스의 생성

- Promise 생성자 함수를 new 연산자와 함께 호출하면 프로미스 객체를 생성한다.
- Promise는 호스트 객체가 아닌 EMCAScript 사양에 정의된 표준 빌트인 객체다.

```javascript
// 프로미스 생성자 함수에 전달되는 excutor 함수.
const excutor = (resolve, reject) => {
  // Promise 함수의 콜백 함수 내부에서 비동기 처리를 수행한다.
  if (/** 비동기 처리 성공 */) {
    resolve('result');
  } else {
    reject('failure reson');
  }
};
// 프로미스 생성
const promise = new Promise(excutor);
```

- 인수로 전달받은 콜백 함수 내부에서 비동기 처리를 수행한다.
- 비동기 처리가 성공하면 콜백 함수의 인수로 전달받은 resolve를 호출하고,
- 실패하면 reject 함수를 호출한다.

> 프로미스는 비동기 처리가 어떻게 진행되고 있는지를 나타내는 상태정보를 갖는다.

|프로미스의 상태 정보|의미|상태 변경 조건|
|:------------------:|:--:|:------------:|
|pending|비동기 처리가 아직 수행되지 않은 상태|프로미스가 생성된 직후 기본 상태|
|fulfilled|비동기 처리가 수행된 상태(성공)|resolve 함수 호출|
|rejected|비동기 처리가 수행된 상태(실패)|reject 함수 호출|

- 비동기 처리 성공: resolve 함수를 호출해 프로미스를 fulfilled 상태로 변경
- 비동기 처리 실패: reject 함수를 호출해 프로미스를 rejected 상태로 변경
- **프로미스의 상태는resolve 혹은 reject 함수를 호출하는 것으로 결정**
- fulfilled, rejected 상태를 settled 상태라고 함. pending이 아닌 상태.
- pending 상태에서는 fulfilled, rejected 상태로 변화할 수 있으나, settled 상태에서는 변화할 수 없음.

```javascript
// fulfilled된 프로미스
const fulfilled = new Promise(resolve => resolve(1));

// rejected된 프로미스
const rejected = new Promise((_, reject) => reject(new Error('error occurred')));
```

- 비동기 처리가 성공하면 프로미스는 pending 상태에서 fulfilled 상태로 변화, 결과값 1
- 비동기 처리가 실패하면 프로미스는 pending 에서 rejected로 변화, Error 객체를 값으로 반환.
- 프로미스는 비동기 처리 상태와 처리 결과를 관리하는 객체.

## 45-3. 프로미스의 후속 처리 메서드

- 프로미스 비동기 처리 상태가 변화하면 후속 처리를 해야 한다.
- 프로미스의 비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출된다.

### 45-3-1. Promise.prototype.then

- then 메서드는 두개의 콜백 함수를 인수로 전달받는다.
- 1) 프로미스가 fulfilled되면 호출 프로미스의 비동기 처리 결과를 인수로 전달 (성공 처리 콜백)
- 2) 프로미스가 rejected 되면 호출 프로미스의 에러를 인수로 전달(실패 처리 콜백)

```javascript
// fulfilled
new Promise(resolve => resolve('fulfilled'))
  .then(v => console.log(v), e => console.error(e)); // fulfilled

// rejected
new Promise((_, reject) => reject(new Error('rejected')))
  .then(v => console.log(v), e => console.error(e)); // Error: rejected
```

### 45-3-2. Promise.prototype.catch

- catch 메서드는 한 개의 콜백함수를 인수로 전달받는다.
- 콜백함수는 프로미스가 rejected상태인 경우만 호출된다.

```javascript
// rejected
new Promise((_, reject) => reject(new Error('rejected')))
  .catch(e => console.log(e)); // Error: rejected
```

- catch 메서드는 then(undefined, onRejected)과 동일하게 동작한다.
- 언제나 프로미스를 반환한다.

```javascript
// rejected
new Promise((_, reject) => reject(new Error('rejected')))
  .then(undefined, e => console.log(e)); // Error: rejected
```

### 45-3-3. Promise.prototype.finally

- finally 메서드는 한개의 콜백 함수를 인수로 전달받는다.
- 콜백 함수는 프로미스의 성공 또는 실패와 상관없이 무조건 한 번 호출된다.
- 프로미스의 상태와 상관없이 공통적으로 수행해야 할 처리 내용이 있을 때 유용.
- finally 메서드도 언제나 프로미스를 반환한다.

```javascript
new Promise(() => {})
  .finally(() => console.log('finally)); // finally
```

- 프로미스로 구현한 비동기 함수 get을 사용해 후속 처리 구현.

```javascript
const promiseGet = url => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) {
        // 성공적으로 응답을 전달 받으면 resolve 함수를 호출한다.
        resolve(JSON.parse(xhr.response));
      } else {
        // 에러 처리를 위해 reject 함수를 호출한다.
        reject(new Error(xhr.status));
      }
    };
  })
};

// promiseGet 함수는 프로미스를 반환한다.
promiseGet('https://jsonplaceholder.typicode.com/posts/1')
  .then(res => console.log(res))
  .catch(err => console.error(err))
  .finally(() => console.log('Bye!'))

```